version: '3'
services:
  web-server:
    restart: always
    build: ./nginx
    container_name: nginx
    volumes:
      - /opt/infographika_web/static:/static
    ports:
      - "80:80"
    links:
      - app:app
  app:
    image: registry.gitlab.com/lexonator/infographika_web
    container_name: app_infographika_web
    restart: always
    volumes:
      - /opt/infographika_web/static:/static
      - /opt/infographika_web/db:/sqlite_data
    ports:
      - "8000:8000"
